- hosts: slave
  tasks:
   - include_vars: "/ws_ansible/dir_var.yml"
   - copy:
      src: "/root/Desktop/jdk-8u171-linux-x64.rpm"
      dest: "/root/"

   - yum:
      name: "jdk-8u171-linux-x64.rpm"
      state: present

   - lineinfile:
       line: "export PATH=/usr/java/jdk1.8.0_171-amd64/bin/:$PATH"
       path: "/root/.bashrc"


   - lineinfile:
       line: "export JAVA_HOME=/usr/java/jdk1.8.0_171-amd64/"
       path: "/root/.bashrc"



   - copy:
      src: "/root/Desktop/hadoop-1.2.1-1.x86_64.rpm"
      dest: "/root/"
 
   - command: "rpm -ivh hadoop-1.2.1-1.x86_64.rpm --force"
   - file:
      path: "/{{ slave }}"
      state: directory 
   - copy:
       dest: "/etc/hadoop/hdfs-site.xml"
       content: |
        <?xml version="1.0"?>
        <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>

        <!-- Put site-specific property overrides in this file. -->

        <configuration>

        <property>
        <name>dfs.data.dir</name>
        <value>/{{ slave }}</value>
        </property>

        </configuration>

   - copy:
       dest: "/etc/hadoop/core-site.xml"
       content: |
        <?xml version="1.0"?>
        <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
 
        <!-- Put site-specific property overrides in this file. -->

        <configuration>
 
        <property>
        <name>fs.default.name</name>
        <value>hdfs://{{ mip1 }}:9001</value>
        </property>

        </configuration>


   - command: "hadoop-daemon.sh start datanode"  
   

